# Age-length keys {#alk}

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(lubridate)
library(viridis)
library(ggmisc)
library(tidyices)
```

```{r}
hh <- read_rds("data/nsibts_hh.rds")
hl <- read_rds("data/nsibts_hl.rds")
ca <- read_rds("data/nsibts_ca.rds")
```

## Quick overview

```{r, message = FALSE, warning = FALSE}
# here ignore year, quarter and area
alk <- 
  ca %>% 
  filter(!is.na(age)) %>% 
  # get round fish area - not needed at this stage
  left_join(hh %>% select(id, area)) %>% 
  # round length to the neares length class
  #   ?? should one use floor here?
  mutate(length = as.integer(round(length, 0))) %>% 
  group_by(latin, age, length) %>% 
  # not sure if i am supposed to summarise the noatalk
  #  or just count the line, here count the lines
  summarise(n = n()) %>% 
  ungroup()
# probability that a certain length class is of certain age
alk <- 
  alk %>% 
  group_by(length) %>% 
  mutate(p = n/sum(n, na.rm = TRUE))  %>% 
  ungroup()
alk %>% 
  ggplot(aes(age, length, fill = p)) +
  geom_raster() +
  scale_fill_viridis(direction = -1)
```

We see in the figure above that something is rotten in the state of denmar, "old" fish but with very small length. This is likely an error in the lngtcode field

```{r}
alk %>% 
  ggplot(aes(length, p, fill = factor(age))) + 
  geom_col() + 
  scale_fill_crayola(name = "Age") +
  scale_x_continuous("Length [cm]", breaks = seq(0, 150, by = 10)) +
  scale_y_continuous("Probability", breaks = seq(0, 1, by = 0.1))
```

Again the error creeps in.

```{r}
hl %>% 
  filter(latin == "Gadus morhua") %>% 
  mutate(length = round(length, 0)) %>% 
  group_by(length) %>% 
  summarise(n = n()) %>% 
  ggplot(aes(length, n)) +
  geom_col() +
  scale_x_continuous("Length [cm]", breaks = seq(0, 150, by = 10))
alk %>% 
  filter(length %in% c(40, 45, 50, 55, 60)) %>% 
  ggplot(aes(age, p)) +
  geom_point() +
  geom_line() +
  facet_grid(length ~ .)
```

## Year, quarter, species

```{r}
common <- c("Clupea harengus", "Sprattus sprattus", "Gadus morhua",
            "Melanogrammus aeglefinus", "Merlangius merlangus", "Pollachius virens",
            "Trisopterus esmarkii", "Scomber scombrus", "Pleuronectes platessa")
alk <- 
  ca %>% 
  filter(!is.na(age)) %>% 
  # get round fish area - actually ignored here
  left_join(hh %>% select(id, area)) %>% 
  filter(!is.na(area)) %>% 
  id_separate() %>% 
  as_tibble() %>% 
  # round length to the neares length class
  #   ?? should one use floor here?
  mutate(length = as.integer(round(length, 0))) %>% 
  group_by(year, quarter, latin, age, length) %>% 
  # not sure if i am supposed to summarise the noatalk
  #  or just count the line, here count the lines
  summarise(n = n()) %>% 
  ungroup() %>%
  group_by(year, quarter, latin, length) %>% 
  mutate(p = n/sum(n, na.rm = TRUE))  %>% 
  ungroup() %>% 
  filter(latin %in% common)
le <- 
  cpue_per_length_per_haul(hh = hh, hl = hl) %>% 
  id_separate() %>% 
  group_by(year, quarter, latin, length) %>% 
  summarise(n = sum(n)) %>% 
  filter(latin %in% common)
x <-
  alk %>%
  select(-n) %>% 
  left_join(le %>% mutate(length = length/10)) %>% 
  group_by(year, quarter, latin, age) %>% 
  summarise(n = sum(p * n, na.rm = TRUE))
x %>% 
  filter(latin == "Melanogrammus aeglefinus",
         quarter == 1,
         age %in% 1:10) %>% 
  mutate(yc = year - age) %>% 
  ggplot(aes(year, n, fill = factor(yc))) +
  geom_col() +
  facet_grid(age ~ ., scale = "free_y") +
  scale_fill_crayola() +
  theme(legend.position = "none") +
  scale_y_continuous(NULL, NULL) +
  labs(x = NULL)
```

## Comparison with datras service product

### ALK

**Pleuronectes platessa**:

```{r, message = FALSE}
alk.dsp <- read_csv("data-raw/ALK.csv")
alk.dsp %>% filter(Species == "Pleuronectes platessa", Year == 2005, Quarter == 1) -> x
x1 <-
  x %>% 
  gather(age, n, Age_0:Age_10, convert = TRUE) %>% 
  mutate(n = as.integer(n)) %>%
  separate(age, c("dummy", "age"), convert = TRUE) %>% 
  filter(!is.na(n)) %>% 
  group_by(age) %>% 
  summarise(n.dsp = sum(n, na.rm = TRUE))
d <- 
  ca %>% 
  right_join(hh %>% filter(haulval == "V", !is.na(area)) %>% select(id)) %>% 
  id_separate() %>% 
  filter(latin == "Pleuronectes platessa",
         year == 2005,
         quarter == 1)
x2 <-
  d %>% 
  group_by(age) %>% 
  summarise(n.tidy = sum(n))
x1 %>% 
  full_join(x2)
```

**Merlangus merlangus**:

```{r, message = FALSE}
alk.dsp <- read_csv("data-raw/ALK.csv")
alk.dsp %>% filter(Species == "Merlangius merlangus", Year == 2005, Quarter == 1) -> x
x1 <-
  x %>% 
  gather(age, n, Age_0:Age_10, convert = TRUE) %>% 
  mutate(n = as.integer(n)) %>%
  separate(age, c("dummy", "age"), convert = TRUE) %>% 
  filter(!is.na(n)) %>% 
  group_by(age) %>% 
  summarise(n.dsp = sum(n, na.rm = TRUE))
d <- 
  ca %>% 
  right_join(hh %>% filter(haulval == "V", !is.na(area)) %>% select(id)) %>% 
  id_separate() %>% 
  filter(latin == "Merlangius merlangus",
         year == 2005,
         quarter == 1)
x2 <-
  d %>% 
  group_by(age) %>% 
  summarise(n.tidy = sum(n))
x1 %>% 
  full_join(x2)
```

### Indices

```{r}
# May need to get newer version of Indices.csv
ind <- read_csv("data-raw/Indices.csv")
colnames(ind) <- tolower(colnames(ind))
```

